import turtle

windows = turtle.Screen()
windows.bgcolor("#1A2A40")
windows.setup(1280, 720)
windows.title("Turtle Artwork!")
def draw_square():
    Turtuly = turtle.Turtle()
    Turtuly.shape("turtle")
    Turtuly.color("#E00B27")
    Turtuly.speed(0)
    Turtuly.color("#EBF4F7")
    for i in range(100):
        Turtuly.circle(150)
        Turtuly.left(6)
    Turtuly.color("#F2A30F")
    for i in range(100):
        Turtuly.forward(200)
        Turtuly.right(120)
        Turtuly.forward(200)
        Turtuly.right(120)
        Turtuly.forward(200)
        Turtuly.right(120)
        Turtuly.left(4)
    Turtuly.color("#E00B27")
    for i in range(200):
        Turtuly.forward(120)
        Turtuly.right(90)
        Turtuly.forward(100)
        Turtuly.right(90)
        Turtuly.forward(120)
        Turtuly.right(90)
        Turtuly.forward(100)
        Turtuly.right(90)
        Turtuly.right(2)
draw_square()